version: '3'

services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  memcached:
    image: memcached:alpine

  rabbitmq:
    image: rabbitmq:3
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASSWORD}

  awx_web:
    image: ansible/awx_web:latest
    depends_on:
      - postgres
      - memcached
      - rabbitmq
    ports:
      - "8080:8052"
    environment:
      SECRET_KEY: ${AWX_SECRET_KEY}
      AWX_ADMIN_USER: ${AWX_USERNAME}
      AWX_ADMIN_PASSWORD: ${AWX_PASSWORD}
      AWX_API_URL: "http://awx_web:8052"
      AWX_TASK_ENV: "default"
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      AWX_PROJECTS_ROOT: "/var/lib/awx/projects"
      AWX_ISOLATED_DATA_VOLUME: "/var/lib/awx/awxcompose"

  awx_task:
    image: ansible/awx_task:latest
    depends_on:
      - awx_web
    environment:
      SECRET_KEY: ${AWX_SECRET_KEY}
      AWX_ADMIN_USER: ${AWX_ADMIN_USER}
      AWX_ADMIN_PASSWORD: ${AWX_ADMIN_PASSWORD}
      AWX_API_URL: "http://awx_web:8052"
      AWX_TASK_ENV: "default"
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      AWX_PROJECTS_ROOT: "/var/lib/awx/projects"
      AWX_ISOLATED_DATA_VOLUME: "/var/lib/awx/awxcompose"

volumes:
  postgres_data: